### ISSUE TITLE
Add new intent: travel

### ISSUE THREAD

**Issue by RohitRathore1** [the-vision/jarvis-core#14]
https://github.com/the-vision/jarvis-core/wiki

**Comment by sunchit17** [comment]
I would like to work on this issue

**Comment by RohitRathore1** [comment]
@sunchit17 I have assigned this issue to you. Let me know if you need any help!

**Comment by sunchit17** [comment]
Thank you

**Comment by sunchit17** [comment]
Should I make a new branch or submit a PR to the master branch itself?

**Comment by RohitRathore1** [comment]
@sunchit17 You have to submit a PR to the master branch itself.

**Comment by sunchit17** [comment]
okay, thanks
