### ISSUE TITLE
Add new intent : movie

### ISSUE THREAD

**Issue by tanisha03** [the-vision/jarvis-core#23]
https://github.com/the-vision/jarvis-core/wiki

**Comment by ripper479** [comment]
i would like to work on this issue.

**Comment by tanisha03** [comment]
@ripper479 you can work on it now !!

**Comment by ripper479** [comment]
thanks

**Comment by RohitRathore1** [comment]
@ripper479 Are you working on this issue?

**Comment by ripper479** [comment]
no please open it for someone

**Comment by tanisha03** [comment]
This issue is open for new assignments!!

**Comment by tanvikapoor29** [comment]
hi, i would like to work in this issue

**Comment by tanisha03** [comment]
@tanvikapoor29 go ahead !!

**Comment by tanvikapoor29** [comment]
hi i created a PR for this issue, please review.

**Comment by tanisha03** [comment]
@tanvikapoor29 mention this issue in your PR

**Comment by RohitRathore1** [comment]
@tanvikapoor29 Are you working on it? If you are having any issue then show me your PR.

**Comment by RohitRathore1** [comment]
@tanvikapoor29 Are you working on it? If you have created PR, then please mention PR number in this issue or this issue number in your PR.
