### ISSUE TITLE
Add new intent : translator

### ISSUE THREAD

**Issue by abnsl0014** [the-vision/jarvis-core#25]
https://github.com/the-vision/jarvis-core/wiki

**Comment by HarshCasper** [comment]
I would like to work on this issue @abnsl0014 

I would be highly obliged if you can assign me this task.

**Comment by abnsl0014** [comment]
@HarshCasper  I have assigned you the issue! Let me know if you have any query.

**Comment by HarshCasper** [comment]
I am currently studying about Rasa NLU and understanding the functioning of the project. I will let you know if I have any query over Slack Channel. Much obliged for your help @abnsl0014

**Comment by abnsl0014** [comment]
Great!

**Comment by tanisha03** [comment]
@HarshCasper are you still working on this ?
