### ISSUE TITLE
Add new intent : Cricket Score

### ISSUE THREAD

**Issue by gan3i** [the-vision/jarvis-core#27]

**Comment by gan3i** [comment]
Hi i would like to work on this issue.

**Comment by abnsl0014** [comment]
@gan3i You can work on one issue at a time.

**Comment by gan3i** [comment]
Hi @abnsl0014 , PR for the other issue is approved , So I thought I could start working on this issue.

**Comment by gan3i** [comment]
Thanks @abnsl0014

**Comment by preeti13456** [comment]
Interested

**Comment by tanisha03** [comment]
@preeti13456 It is already assigned to someone, you can look for other issues.

**Comment by RohitRathore1** [comment]
@gan3i Are you working on this issue?

**Comment by gan3i** [comment]
@TeAmP0is0N  Yes I have already created a PR

**Comment by RohitRathore1** [comment]
@gan3i If you have created PR, then please mention PR number in this issue or this issue number in your PR.

**Comment by gan3i** [comment]
#44 Hi @TeAmP0is0N I have linked the PR here.
