### ISSUE TITLE
Add new intent: bye

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-core#4]
https://github.com/the-vision/jarvis-core/wiki

**Comment by AishwaryaVarma** [comment]
I want to work on this

**Comment by RohitRathore1** [comment]
@AishwaryaVarma I have assigned this issue to you. Let me know if you need any help!

**Comment by hritikksingh** [comment]
@TeAmP0is0N @swapagarwal  if she is not working on this can I give it a try....

**Comment by sgpritam** [comment]
@hritikpapa I have assigned this issue to you. Let me know if you need any help!

**Comment by hritikksingh** [comment]
> @hritikpapa I have assigned this issue to you. Let me know if you need any help!

thank you @sgpritam

**Comment by hritikpapa** [comment]
@sgpritam @TeAmP0is0N @swapagarwal what all function do you want me to add in this
