### ISSUE TITLE
Add new intent: coin

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-core#5]
https://github.com/the-vision/jarvis-core/wiki

**Comment by gan3i** [comment]
Hi I would Like to work on this. would you please assign it to me.

**Comment by sgpritam** [comment]
@gan3i  I have assigned this issue to you. Let me know if you need any help!

**Comment by RohitRathore1** [comment]
@gan3i I have assigned this issue to you. Let @sgpritam know if you need any help!

**Comment by gan3i** [comment]
Hey @sgpritam , I see Model folder when I open the project in gitpod but not when I clone the project, please let me know what am I missing here.

**Comment by sgpritam** [comment]
@gan3i When I run the project on gitpod, I do not see Model Folder
![image](https://user-images.githubusercontent.com/41269164/75678005-a75c4e80-5cb2-11ea-8905-5fd6bf72b071.png)

**Comment by gan3i** [comment]
@sgpritam  I think I am missing something here, I do see the model folder.
![image](https://user-images.githubusercontent.com/28672572/75678251-379a9380-5cb3-11ea-90ba-77db33c5bf08.png)
