### ISSUE TITLE
Add new intent: fact

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-core#6]
https://github.com/the-vision/jarvis-core/wiki

**Comment by sunchit17** [comment]
Can I work on this? after merging PR #20

**Comment by sgpritam** [comment]
@sunchit17 yes sure

**Comment by sgpritam** [comment]
@sunchit17 Yes you can after merge

**Comment by RohitRathore1** [comment]
@sunchit I have assigned this issue to you. Let me know if you need any help!
