### ISSUE TITLE
Add new intent: Time

### ISSUE THREAD

**Issue by csharp489** [the-vision/jarvis-core#68]
Time can be added as a new intent @tanisha03 @swapagarwal @TeAmP0is0N  please assign me this issue
.

**Comment by RohitRathore1** [comment]
@csharp489 Go ahead.

**Comment by RohitRathore1** [comment]
> Time can be added as a new intent @tanisha03 @swapagarwal @TeAmP0is0N please assign me this issue
> .

https://github.com/the-vision/jarvis-core/wiki

**Comment by csharp489** [comment]
@TeAmP0is0N I have added PR please check it #70
