### ISSUE TITLE
Add new intent: hello

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-core#7]
https://github.com/the-vision/jarvis-core/wiki

**Comment by adityabisoi** [comment]
Hey @swapagarwal I want to work on this.

**Comment by RohitRathore1** [comment]
> Hey @swapagarwal I want to work on this.

@adityabisoi I have assigned this issue to you. Let me know if you need any help!

**Comment by adityabisoi** [comment]
@TeAmP0is0N can you please tell me if I should make a MR to ```master``` branch? Also, is there any format for making an MR? Thanks.

**Comment by RohitRathore1** [comment]
@adityabisoi Pull Request? Yeah, you can directly make a PR to the master branch. Just, whatever changes you have done comment it in your pull request.

**Comment by AishwaryaVarma** [comment]
I want to work in this

**Comment by RohitRathore1** [comment]
@AishwaryaVarma Thanks for your interest. Please choose another issue. This one has already been assigned to another person.
