### ISSUE TITLE
Add new intent: Anime

### ISSUE THREAD

**Issue by adityabisoi** [the-vision/jarvis-core#76]
An Anime intent can be added for more features.

@TeAmP0is0N @swapagarwal  Please assign me this issue. Thanks.

**Comment by RohitRathore1** [comment]
@adityabisoi First resolve the previous one, then you can work on it.

**Comment by adityabisoi** [comment]
@TeAmP0is0N I have resolved all the previous ones. Can I get this now?

**Comment by RohitRathore1** [comment]
@adityabisoi Go ahead.
