### ISSUE TITLE
Add new intent: help

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-core#8]
https://github.com/the-vision/jarvis-core/wiki

**Comment by VibavariG** [comment]
I would like to work on this issue

**Comment by RohitRathore1** [comment]
@VibavariG I have assigned this issue to you. Let me know if you need any help!

**Comment by hritikksingh** [comment]
@TeAmP0is0N @swapagarwal  if the assigned person is not working on this, then I want to take up this issue.
