### ISSUE TITLE
Add new intent: motivation

### ISSUE THREAD

**Issue by adityabisoi** [the-vision/jarvis-core#85]
Add intent for fetching motivational speeches and quotes.
@swapagarwal @TeAmP0is0N Please assign this to me.

**Comment by RohitRathore1** [comment]
@adityabisoi Go ahead!

**Comment by AishwaryaVarma** [comment]
assign this to me

**Comment by RohitRathore1** [comment]
@AishwaryaVarma It has been resolved.
