### ISSUE TITLE
Add instructions for testing in README

### ISSUE THREAD

**Issue by adityabisoi** [the-vision/jarvis-core#88]
**Is your feature request related to a problem? Please describe.**
No. This is a documentation-related change.

**Describe the solution you'd like**
Beginners find it difficult to figure out how to run tests to check the intents. An instruction on running the tests would be helpful.

**Describe alternatives you've considered**
The instruction provided should be:

1. Run the commands provided for setup
2. Rename the path in `test.py` from `./models/nlu/default/test` to `./models/nlu/default/<MODEL_ID>`
3. Run ` python test.py` to run tests on the intents.

@swapagarwal @TeAmP0is0N Please assign this issue to me.

**Comment by RohitRathore1** [comment]
@adityabisoi Go Ahead.
