### ISSUE TITLE
Add new intent: joke

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-core#9]
https://github.com/the-vision/jarvis-core/wiki

**Comment by h0m3brew** [comment]
I would like to work on this issue.

**Comment by RohitRathore1** [comment]
@glob4lh3ll I have assigned this issue to you. let me know if you need any help.

**Comment by hritikksingh** [comment]
@TeAmP0is0N @swapagarwal Any one still working on this???

**Comment by RohitRathore1** [comment]
@hritikpapa you can not work on two issues in the same repo. First, finish the previous one then I will assign you.

**Comment by hritikksingh** [comment]
@TeAmP0is0N I already created a PR for the last issue assigned to me, please review it so that I can work on this. :+1:

**Comment by RohitRathore1** [comment]
@hritikpapa I have assigned this issue to you. let me know if you need any help.
